name: Windows Qt Installer

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: windows-latest
        
        steps:
        - name : Checkout repo
          uses : actions/checkout@v4
          
        - name: List available Qt modules
          run: |
            pip install aqtinstall
            python -m aqt install-qt windows desktop 6.5.3 win64_msvc2019_64
          
        - name : Install Qt
          uses : jurplel/install-qt-action@v4
          with:
                version: 6.5.3
                arch: win64_msvc2019_64
                cache: true
                
        - name: Check windeployqt
          run: where windeployqt
                
        - name: Configure project
          run: cmake -B build -DCMAKE_PREFIX_PATH="%Qt6_DIR%" -DCMAKE_BUILD_TYPE=Release
          
        - name: Build project
          run: cmake --build build --config Release
          
        - name: Deploy Qt DLLs
          run: |
            mkdir dist
            mkdir dist\translations
            copy build\Release\*.exe dist\
            copy translations\*.qm dist\translations
            windeployqt dist\NimNN.exe
          
        - name: Install NSIS
          run: choco install nsis -y
          
        - name: Create installer
          run: makensis installer.nsi
          
        - name: Upload installer
          uses: actions/upload-artifact@v4
          with:
            name: NimNN-installer
            path: NimNN-installer.exe
