name: Windows Qt Installer

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: windows-latest
        
        steps:
        - name : Checkout repo
          uses : actions/checkout@v3
          
        - name : Install Qt
          uses : jurplel/install-qt-action@v3
          with:
                version: 6.7.0
                modules: qtbase qtwidgets
                
        - name: Configure project
          run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          
        - name: Build project
          run: cmake --build build --config Release
          
        - name: Install NSIS
          run: choco install nsis -y
          
        - name: Create installer
          run: makensis installer.nsi
          
        - name: Upload installer
          uses: actions/upload-artifact@v3
          with:
            name: NimNN-installer
            path: NimNN-installer.exe
